version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom_php_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - custom_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: myappdb
      DB_USERNAME: myappuser
      DB_PASSWORD: myapppass

  db:
    image: mysql:8.0
    container_name: custom_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: custom_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - custom_network

volumes:
  db_data:

networks:
  custom_network:


